# Generated by Django 5.0.2 on 2024-11-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='farm_location',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
